### PR TITLE
fix: fix #129 made yes_no not break terminal

### LINKED ISSUE #129: make functions that use cin pipe/service safe
Functions like io::get_user_yes_or_no will loop infinitely if cin is not available currently.

### PR DESCRIPTION
**Pull request by GaeaKat**

### CODE REVIEW

File: src/data/include/data/io/wait_for_enter.hpp [hunk 1]
```diff
@@ -6,12 +6,20 @@
...
+    /// @warning Will cause an infinite loop if used in a non-terminal enviroment
     void wait_for_enter (std::string message = "Press enter to continue...");
 
-    bool get_user_yes_or_no (std::string message = "");
+
+    /// @brief Waits for user to respond to a message with yes or no
+    /// @param message question to ask user
+    /// @param default_value default value to return if enter pressed or no terminal
+    /// @return true if yes, false otherwise, or no value if nothing was chosen and no default
+    std::optional<bool> get_user_yes_or_no (std::string message ,std::string default_value="Y");
```
Comment (DanielKrawisz) [inline src/data/include/data/io/wait_for_enter.hpp:22]: Just return bool. You don't need an optional bool. Use bool default_value = true for the default value, not yes or no. 

Also if you intend to use optional in the future, use maybe from maybe.hpp. This extends optional to make it slightly more convenient.

Comment (GaeaKat) [reply src/data/include/data/io/wait_for_enter.hpp:22]: Rewrote this to use maybe, and return a plain bool
